[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "sampleproject-rs"
version = "0.0.1"
requires-python = ">=3.9"

[tool.maturin]
bindings = "bin"
strip = true
