name: Run tests

on: [push]

jobs:
  rust:
    name: cargo test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --all-features

  python:
    needs: rust
    name: pytest on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install (Linux / macOS)
        if: ! startsWith(matrix.os, 'windows')
        run: |
          python -m venv .venv --upgrade-deps
          source .venv/bin/activate
          pipx run maturin develop -E test
      - name: Install (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          python -m venv .venv --upgrade-deps
          .venv\Scripts\activate
          pipx run maturin develop -E test
      - name: Run tests (Linux / macOS)
        if: ! startsWith(matrix.os, 'windows')
        run: |
          source .venv/bin/activate
          pytest
      - name: Run tests (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          .venv\Scripts\activate
          pytest
