name: Run tests

on: [push]

jobs:
  rust:
    name: cargo test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --all-features

  python:
    needs: rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install
        run: |
          python -m venv .venv --upgrade-deps
          source .venv/bin/activate
          pipx run maturin develop -E test
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest
